### ISSUE TITLE
Support for PIPS-S and PIPS-IPM?

### ISSUE THREAD

**Issue by adowling2** [StructJuMP/StructJuMP.jl#24]
Are there plans for this package to support PIPS-S and PIPS-IPM in addition to PIPS-NLP and DSP? As a modeler, I'd greatly appreciate one interface (StructJuMP?) that works with all of these solvers.

**Comment by joehuchette** [comment]
No concrete plans, but it would certainly be nice to have. It's just a matter of someone writing the glue code :)

**Comment by mlubin** [comment]
CC @cnpetra

**Comment by cnpetra** [comment]
interfacing with PIPS-S and PIPS-IPM, which solve only LPs/convex QPs, is of low priority (unless you have a stringent need for them). This is because PIPS-NLP can already solve LPs/QPs...

BTW, when this will happen, there will be no model modifications needed, all of them will be behind the same interface.
